apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketchat-mongodb
  labels:
    volume: rocketchat-mongodb
spec:
  capacity:
    storage: 600Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /root_vdm_4/PNN1PSCDF002/INFRA/rocketchat-mongodb
    server: "[2801:8e:802::1]"
  persistentVolumeReclaimPolicy: Retain
