apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 10.8.2.182
    ports:
      - port: 1
  - addresses:
      - ip: 10.8.2.183
    ports:
      - port: 1
  - addresses:
      - ip: 10.8.2.184
    ports:
      - port: 1
